name: Pre Commit Check

on:
  push:
    branches: [ "master", "qa" ]
    paths-ignore:
      - "docs/reference/**"
      - "docs/**/*.rst"
      - "LICENSE"
  pull_request:
    branches: [ "master", "qa" ]
    paths-ignore:
      - "docs/reference/**"
      - "docs/**/*.rst"
      - "LICENSE"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
    - name: Set up Python environment and install dependencies
      uses: ./.github/actions/camel_install
      with:
        python-version: "3.10"
    - name: Run pre-commit
      run: |
        source .venv/bin/activate
        pre-commit run --all-files
      shell: bash
